ASP.NET/GardenApp/src/webUI/GardenApp.Mvc/Controllers/UserController.cs
using GardenApp.DataTransferObjects.Requests;
using GardenApp.Mvc.Models;
using GardenApp.Services;
using Mapster;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GardenApp.Mvc.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        public UserController(IUserService userService)
        {
            this.userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login(string? redirectUrl)
        {
            ViewBag.RedirectUrl = redirectUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginViewModel model, string? redirectUrl)
        {
            if (ModelState.IsValid)
            {
                var user = await userService.ValidateUser(model.Adapt<UserLoginRequest>());
                if(user != null)
                {
                    // Claim-based authentication
                    Claim[] claims = new Claim[]
                    {
                        new Claim(ClaimTypes.Name, user.FullName),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Role, user.Role),
                    };
                    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(principal);
                    if (!string.IsNullOrEmpty(redirectUrl) && Url.IsLocalUrl(redirectUrl))
                    {
                        return Redirect(redirectUrl);
                    }
                    return Redirect("/");
                }
                ModelState.AddModelError("login", "Wrong username or password!");
            }
            return View();
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ASP.NET/GardenApp/src/webUI/GardenApp.Mvc/ViewComponents/BasketLinkViewComponent.cs
using GardenApp.Mvc.Extensions;
using GardenApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace GardenApp.Mvc.ViewComponents
{
    public class BasketLinkViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var plantCollection = HttpContext.Session.GetJson<PlantCollection>("basket");
            return View(plantCollection);
        }
    }
}

ASP.NET/GardenApp/src/webUI/GardenApp.Mvc/ViewComponents/MenuViewComponent.cs
using GardenApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace GardenApp.Mvc.ViewComponents
{
    public class MenuViewComponent: ViewComponent
    {
        private readonly IPlantTypeService plantTypeService;
        public MenuViewComponent(IPlantTypeService plantTypeService)
        {
            this.plantTypeService = plantTypeService;
        }
        public IViewComponentResult Invoke()
        {
            var plantTypes = plantTypeService.GetPlantTypesForList();
            return View(plantTypes);
        }
    }
}

ASP.NET/GardenApp/src/webUI/GardenApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GardenApp.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GardenApp.Mvc.styles.css" asp-append-version="true" />
    <link href="~/alertifyjs/css/alertify.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GardenApp.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("BasketLink")
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- menu -->
            <div class="row">
                <div class="col-2">@await Component.InvokeAsync("Menu")</div>
                <div class="col-10">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GardenApp.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/alertifyjs/alertify.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET/GardenApp/src/webUI/GardenApp.Mvc/Views/Shared/_PlantDisplay.cshtml
@model PlantDisplayResponse

@{
    var rateStar = new string('⭐', (int)Model.Rating);
}

<div class="card my-2">
    <img src="@Model.ImageUrl" class="img-fluid center-image my-2" />
    <div class="card-body">
        <h4 class="card-title">@Model.Name</h4>
        <p class="card-text"> @rateStar </p>
        <p class="card-text">@Model.Price $</p>
        <button class="btn btn-success basket" data-id="@Model.Id">Add To Cart</button>
    </div>
</div>